from typing import Final

TEAM_COLUMNS: Final = ("team", "home_team", "away_team")

# cleaned name -> canonical name. Identity entries are known names that need no alias.
_TABLE: dict[str, str] = {
    # ENG-Premier League: short and alternative names
    "man united": "manchester united",
    "man utd": "manchester united",
    "manchester utd": "manchester united",
    "man city": "manchester city",
    "newcastle": "newcastle united",
    "newcastle utd": "newcastle united",
    "nott'm forest": "nottingham forest",
    "nott'ham forest": "nottingham forest",
    "sheffield utd": "sheffield united",
    "sheffield weds": "sheffield wednesday",
    "leeds": "leeds united",
    "spurs": "tottenham",
    "tottenham hotspur": "tottenham",
    "west brom": "west bromwich albion",
    "wolves": "wolverhampton wanderers",
    "west ham united": "west ham",
    "brighton & hove albion": "brighton",
    "brighton and hove albion": "brighton",
    "qpr": "queens park rangers",
    "leicester": "leicester city",
    "norwich": "norwich city",
    "cardiff": "cardiff city",
    "swansea": "swansea city",
    "stoke": "stoke city",
    "hull": "hull city",
    "huddersfield": "huddersfield town",
    "luton": "luton town",
    "ipswich": "ipswich town",
    "wigan": "wigan athletic",
    "bolton": "bolton wanderers",
    "birmingham": "birmingham city",
    "blackburn": "blackburn rovers",
    "charlton": "charlton athletic",
    "derby": "derby county",
    "coventry": "coventry city",
    "bradford": "bradford city",
    # ENG-Premier League (no alias needed)
    "arsenal": "arsenal",
    "aston villa": "aston villa",
    "blackpool": "blackpool",
    "bournemouth": "bournemouth",
    "brentford": "brentford",
    "burnley": "burnley",
    "chelsea": "chelsea",
    "crystal palace": "crystal palace",
    "everton": "everton",
    "fulham": "fulham",
    "liverpool": "liverpool",
    "middlesbrough": "middlesbrough",
    "portsmouth": "portsmouth",
    "reading": "reading",
    "southampton": "southampton",
    "sunderland": "sunderland",
    "watford": "watford",
    # ESP-La Liga
    "alaves": "alaves",
    "almeria": "almeria",
    "athletic club": "athletic club",
    "atletico madrid": "atletico madrid",
    "barcelona": "barcelona",
    "cadiz": "cadiz",
    "celta vigo": "celta vigo",
    "cordoba": "cordoba",
    "deportivo la coruna": "deportivo la coruna",
    "eibar": "eibar",
    "elche": "elche",
    "espanyol": "espanyol",
    "getafe": "getafe",
    "girona": "girona",
    "granada": "granada",
    "las palmas": "las palmas",
    "leganes": "leganes",
    "levante": "levante",
    "malaga": "malaga",
    "mallorca": "mallorca",
    "osasuna": "osasuna",
    "rayo vallecano": "rayo vallecano",
    "real betis": "real betis",
    "real madrid": "real madrid",
    "real oviedo": "real oviedo",
    "real sociedad": "real sociedad",
    "real valladolid": "real valladolid",
    "sd huesca": "sd huesca",
    "sevilla": "sevilla",
    "sporting gijon": "sporting gijon",
    "valencia": "valencia",
    "villarreal": "villarreal",
    # FRA-Ligue 1
    "ajaccio": "ajaccio",
    "amiens": "amiens",
    "angers": "angers",
    "auxerre": "auxerre",
    "bordeaux": "bordeaux",
    "brest": "brest",
    "caen": "caen",
    "clermont foot": "clermont foot",
    "dijon": "dijon",
    "evian thonon gaillard": "evian thonon gaillard",
    "gfc ajaccio": "gfc ajaccio",
    "guingamp": "guingamp",
    "le havre": "le havre",
    "lens": "lens",
    "lille": "lille",
    "lorient": "lorient",
    "lyon": "lyon",
    "marseille": "marseille",
    "metz": "metz",
    "monaco": "monaco",
    "montpellier": "montpellier",
    "nancy": "nancy",
    "nantes": "nantes",
    "nice": "nice",
    "nimes": "nimes",
    "paris fc": "paris fc",
    "paris saint germain": "paris saint germain",
    "reims": "reims",
    "rennes": "rennes",
    "saint-etienne": "saint-etienne",
    "sc bastia": "sc bastia",
    "strasbourg": "strasbourg",
    "toulouse": "toulouse",
    "troyes": "troyes",
    # GER-Bundesliga
    "arminia bielefeld": "arminia bielefeld",
    "augsburg": "augsburg",
    "bayer leverkusen": "bayer leverkusen",
    "bayern munich": "bayern munich",
    "bochum": "bochum",
    "borussia dortmund": "borussia dortmund",
    "borussia mgladbach": "borussia mgladbach",
    "darmstadt": "darmstadt",
    "eintracht frankfurt": "eintracht frankfurt",
    "fc cologne": "fc cologne",
    "fc heidenheim": "fc heidenheim",
    "fortuna duesseldorf": "fortuna duesseldorf",
    "freiburg": "freiburg",
    "greuther fuerth": "greuther fuerth",
    "hamburger sv": "hamburger sv",
    "hannover 96": "hannover 96",
    "hertha berlin": "hertha berlin",
    "hoffenheim": "hoffenheim",
    "holstein kiel": "holstein kiel",
    "ingolstadt": "ingolstadt",
    "mainz 05": "mainz 05",
    "nuernberg": "nuernberg",
    "paderborn": "paderborn",
    "rasenballsport leipzig": "rasenballsport leipzig",
    "schalke 04": "schalke 04",
    "st pauli": "st pauli",
    "union berlin": "union berlin",
    "vfb stuttgart": "vfb stuttgart",
    "werder bremen": "werder bremen",
    "wolfsburg": "wolfsburg",
    # ITA-Serie A
    "ac milan": "ac milan",
    "atalanta": "atalanta",
    "benevento": "benevento",
    "bologna": "bologna",
    "brescia": "brescia",
    "cagliari": "cagliari",
    "carpi": "carpi",
    "cesena": "cesena",
    "chievo": "chievo",
    "como": "como",
    "cremonese": "cremonese",
    "crotone": "crotone",
    "empoli": "empoli",
    "fiorentina": "fiorentina",
    "frosinone": "frosinone",
    "genoa": "genoa",
    "inter": "inter",
    "juventus": "juventus",
    "lazio": "lazio",
    "lecce": "lecce",
    "monza": "monza",
    "napoli": "napoli",
    "palermo": "palermo",
    # Parma went bankrupt in 2015 and was refounded; same club, same Transfermarkt id.
    "parma": "parma calcio 1913",
    "parma calcio 1913": "parma calcio 1913",
    "pescara": "pescara",
    "pisa": "pisa",
    "roma": "roma",
    "salernitana": "salernitana",
    "sampdoria": "sampdoria",
    "sassuolo": "sassuolo",
    "spal 2013": "spal 2013",
    "spezia": "spezia",
    "torino": "torino",
    "udinese": "udinese",
    "venezia": "venezia",
    "verona": "verona",
}

# Every canonical name is also a key of itself.
ALIASES: Final[dict[str, str]] = {**{v: v for v in _TABLE.values()}, **_TABLE}
__all__ = ["ALIASES", "TEAM_COLUMNS"]
