[project]
name = "money-printer-research"
version = "0.0.1"
description = "A short description of the project."
authors = [{ name = "Mikhail Akhsakov", email = "your.email@example.com" }]
readme = "README.md"
keywords = ["python"]
classifiers = [
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.12"
dependencies = [
    "kaggle>=2.2.4",
    "kagglehub>=1.0.2",
    "matplotlib>=3.11.2",
    # Add your project dependencies here
    "polars>=1.44.2",
    "pyarrow>=25.0.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "scikit-learn>=1.9.1",
    "scipy-stubs>=1.18.1.1",
    "soccerdata>=1.9.1",
]

[project.urls]
Homepage = "https://Ax-47.github.io/money-printer-research/"
Repository = "https://github.com/Ax-47/money-printer-research"
Documentation = "https://Ax-47.github.io/money-printer-research/"

requires-python = ">=3.9,<4.0"

[project.scripts]
collect_data = "money_printer_research:collect_data"
clean_data = "money_printer_research:clean_data"
feature_importance = "money_printer_research:exec_feature_importance"
# DEV SETTING
[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "jupyterlab>=4.3.1",
    "pyright>=1.1.398",
    "pytest-cov>=6.0.0",
    "pytest>=8.1.1",
    "ruff>=0.9.4",
    "toml-sort>=0.24.2",
    "uv>=0.5.26",
    "pre-commit>=4.1.0",
    "basedpyright>=1.40.2",
]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-include-markdown-plugin>=7.1.4",
    "mkdocs-jupyter>=0.25.1",
    "mkdocs-material>=9.6.3",
    "mkdocstrings[python]>=0.15.0",
    "pymdown-extensions>=10.14.3",
]

# DEV SETTING
[tool.uv]
default-groups = ["dev"]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
[tool.ruff.lint.per-file-ignores]
"notebooks/*" = ["E501", "F821"]
# DEV SETTING
# ruff.toml file is used.
[tool.ruff]

# DEV SETTING
# pytest.ini file is used.
[tool.pytest]

# DEV SETTING
# .coveragerc file is used. A pytest fixture in .conftest.py is used to create coverage file/report directory.
[tool.coverage]

# DEV SETTING
# pyrightconfig.json file is used. NOTE: Ensure to set the python version correctly.
[tool.pyright]

# DEV SETTING
# NOTE: to sort, run: "uv run toml-sort pyproject.toml"
[tool.tomlsort]
in_place = true
no_sort_tables = true
sort_inline_arrays = true
spaces_before_inline_comment = 4
spaces_indent_inline_array = 4

[tool.hatch.build.targets.wheel]
packages = ["src/money_printer_research"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
