# Application configuration settings
[kaggle]
handle = "marcohuiii/english-premier-league-epl-match-data-2000-2025"
output_dir = "data/raw/matches"

[fbref]
league = "ENG-Premier League"
start_year = 2015
end_year = 2025
out_dir = "data/raw/lineups"
cache_dir = "data/FBref"

[understat]
league = "ENG-Premier League"
start_year = 2014
end_year = 2025
out_dir = "data/raw/player_stats"
schedule_file = "data/raw/xg_schedule.csv"
cache_dir = "data/Understat"

[clean]
out_dir = "data/clean"
[api_settings]
host = "0.0.0.0"
port = 8000
